Service:
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      FileArtifactRelation:
        '{{ computenest::file::LYH-RAIN_dify-test-docker-compose }}':
          ArtifactId: artifact-fdb192c6addb4d1390e7
          ArtifactVersion: '3'
      SupplierTemplateConfigs:
        - Name: 单机版
          Url: https://service-info-public.oss-cn-hangzhou.aliyuncs.com/1563457855438522/cn-hangzhou/templatef30a2b456a564c00a1a8.yaml
          AllowedRegions:
            - cn-hangzhou
            - cn-shanghai
            - cn-beijing
    TemplateConfigs:
      - Name: 单机版
        Url: https://service-info-public.oss-cn-hangzhou.aliyuncs.com/1563457855438522/cn-hangzhou/template385450054a8e4d73888e.yaml
        AllowedRegions:
          - cn-hangzhou
          - cn-shanghai
          - cn-beijing
        PredefinedParameters: []
        HiddenParameterKeys: []
        DeployScene: ECS
  OperationMetadata:
    StatusOperationConfigs:
      - TemplateName: 单机版
        SupportOperations:
          - Start
          - Stop
          - Restart
    SupportBackup: true
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: Service description
    Image: https://service-info-public.oss-cn-hangzhou.aliyuncs.com/1853370294850618/service-image/bfd30cc4-e959-4093-b5cb-77a05058b911.png
    Name: LYH-RAIN/dify-test-j5f4
  ShareType: Public
  ApprovalType: Manual
Artifact:
  Artifact_1:
    ArtifactType: File
    ArtifactName: LYH-RAIN_dify-test-docker-compose
    Description:
    ArtifactProperty:
      Url: 
        https://computenest-artifacts-draft-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com/1563457855438522/cn-hangzhou/04a890a4b36b4ba18567/docker_compose.tar?Expires=1732252909&OSSAccessKeyId=LTAI5tCYphFhocJemeMWmXst&Signature=44PphAkXeMgz6GsvC2ckOCi%2BfSc%3D&response-content-type=application%2Foctet-stream
    SupportRegionIds:
      - cn-qingdao
      - cn-beijing
      - cn-zhangjiakou
      - cn-huhehaote
      - cn-wulanchabu
      - cn-hangzhou
      - cn-shanghai
      - cn-shenzhen
      - cn-heyuan
      - cn-guangzhou
      - cn-chengdu
      - cn-hongkong
      - ap-northeast-1
      - ap-southeast-1
      - ap-southeast-3
      - ap-southeast-5
      - ap-southeast-6
      - us-east-1
      - us-west-1
      - eu-west-1
      - eu-central-1
      - me-east-1
      - cn-nanjing
      - cn-fuzhou
      - ap-southeast-7
      - ap-northeast-2
      - cn-wuhan-lr
